name: Docker integration testing
on: [push]

jobs:
  test:
    name: Run examples
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: docker info
    - run: .ci/frontend-integration-tests.sh
