name: Docker integration
on: [push]

jobs:
  test:
    name: Run examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker info
      - run: .ci/test-reverse-example.sh
      - run: .ci/test-download-example.sh
      - run: .ci/test-ssh-mount-example.sh
