name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features  --verbose

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/components-nightly@v1
      id: component
      with:
        component: rustfmt
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ steps.component.outputs.toolchain }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/components-nightly@v1
      id: component
      with:
        component: clippy
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ steps.component.outputs.toolchain }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
